output "remix_frontend_public_ip" {
  description = "the public ip of the fronend"
  value = aws_instance.remix-frontend.public_ip
}

resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    tf_frontend_public_ip: ${aws_instance.remix-frontend.public_ip}
    DOC
  filename = "../../ansible/tf_ansible_vars_file.yml"
}
