---
- name: Provision frontend
  hosts: frontend
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Install pip
      ansible.builtin.apt:
        update_cache: true
        name: python3-pip

    - name: Install aptitude using apt
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true
        force_apt_get: true

    - name: Install required system packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        [
          "apt-transport-https",
          "ca-certificates",
          "curl",
          "software-properties-common",
          "python3-pip",
          "virtualenv",
          "python3-setuptools",
        ]

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        update_cache: true
        state: latest

    - name: Install docker-py
      ansible.builtin.pip:
        name: docker-py

    - name: Enable Docker services
      service:
        name: "docker"
        state: started
        enabled: true

    - name: Check if container is running
      ansible.builtin.command: docker ps

    - name: Run frontend image
      community.docker.docker_container:
        name: remix-demo
        image: 3steel/remix-demo:latest
        state: started
        published_ports: 3000:3000

    - name: Show running images
      ansible.builtin.command: docker images
